import io.cucumber.java.en.And;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class BlazeDemoSteps {
    private WebDriver driver;

    @When("I navigate to {string}")
    public void iNavigateTo(String url) {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.get(url);
        driver.get("https://blazedemo.com/");
        driver.manage().window().setSize(new Dimension(672, 690));
    }

    @And("I select {string} as origin")
    public void iSelectAsOrigin(String origin) {
        driver.findElement(By.name("fromPort")).click();
        {
            WebElement dropdown = driver.findElement(By.name("fromPort"));
            dropdown.findElement(By.xpath("//option[. = '" + origin + "']")).click();
        }
    }

    @And("I select {string} as destination")
    public void iSelectAsDestiny(String destination) {
        driver.findElement(By.name("toPort")).click();
        {
            WebElement dropdown = driver.findElement(By.name("toPort"));
            dropdown.findElement(By.xpath("//option[. = '"+ destination +"']")).click();
        }
    }

    @And("click on Find Flights")
    public void clickOnFindFlights() {
        driver.findElement(By.cssSelector(".btn-primary")).click();
        driver.findElement(By.cssSelector("h3")).click();
    }

    @Then("Im redirected to {string}")
    public void imRedirectedTo(String reserves_url) {
        assertThat(driver.getCurrentUrl(), is(reserves_url));
    }

    @And("the page's title is {string}")
    public void thePageSTitleIs(String title) {
        assertThat(driver.findElement(By.cssSelector("h3")).getText(), is(title));
    }




}
